# Refer to https://ko.build/configuration/#overriding-go-build-settings
builds:
- id: holos
  dir: .
  main: ./cmd/holos
  env:
  - GOPRIVATE=github.com/holos-run/\*
  ldflags:
  - -s
  - -w
  - -X
  # Makefile provides GIT_DETAIL and GIT_SUFFIX.
  - github.com/holos-run/holos/version.GitDescribe={{.Env.GIT_DETAIL}}{{.Env.GIT_SUFFIX}}
