---
# Source: CUE apiObjects.PostgresCluster.holos
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: holos
  namespace: dev-holos
  labels:
    app.holos.run/environment: dev
    app.holos.run/name: holos
    app.holos.run/component: infra
    render.holos.run/component: dev-holos-infra
  annotations: {}
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.1-0
  instances:
    - affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: holos
                topologyKey: topology.kubernetes.io/zone
              weight: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: db
      replicas: 1
  port: 5432
  postgresVersion: 16
  users:
    - databases:
        - holos
      name: holos
      options: SUPERUSER
  backups:
    pgbackrest:
      global:
        archive-async: "y"
        archive-push-queue-max: 100MiB
        spool-path: /pgdata/backups
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-2
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
