apiVersion: v1
kind: ServiceAccount
metadata:
  name: holos
  namespace: dev-holos
  labels:
    app.holos.run/environment: dev
    app.holos.run/name: holos
---
# Source: CUE apiObjects.Service.holos
apiVersion: v1
metadata:
  name: holos
  namespace: dev-holos
  labels:
    app.holos.run/environment: dev
    app.holos.run/name: holos
  annotations: {}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: server
  ports:
    - appProtocol: http2
      name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - appProtocol: http
      name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
kind: Service
---
# Source: CUE apiObjects.ReferenceGrant.istio-gateways
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: istio-gateways
  namespace: dev-holos
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: istio-gateways
  to:
    - group: ""
      kind: Service
