# Job to fetch credentials for SecretStore to auth to a GKE Autopilot cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: seedcreds
spec:
  template:
    spec:
      containers:
      - name: gcloud
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
