---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "{{ .Namespace }}"
resources:
  - "https://raw.githubusercontent.com/argoproj/argo-cd/v{{ .Version }}/manifests/install.yaml"
