apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-iam

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: prod-iam-obs
    vendor: holos

resources:
- grafana
- prometheus
- alertmanager
