---
# Source: CUE apiObjects.Job.holos
apiVersion: batch/v1
kind: Job
metadata:
  name: holos-init
  namespace: dev-holos
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "2"
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 5
  template:
    spec:
      containers:
        - name: holos
          image: quay.io/holos-run/holos:v0.87.2-26-g3845174
          imagePullPolicy: IfNotPresent
          command:
            - /app/bin/holos
            - server
            - init
            - --log-level=debug
            - --log-format=json
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: holos-app
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 512Mi
      restartPolicy: OnFailure
      serviceAccountName: holos
      securityContext:
        seccompProfile:
          type: RuntimeDefault
