name: Container

# Only allow actors with write permission to the repository to trigger this
# workflow.
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to build (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Save Dockerfile from main
        run: |
          mkdir -p /tmp/docker
          cp Dockerfile /tmp/docker/
      - name: Set tag from trigger event
        id: opts
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ steps.opts.outputs.tag }}
          clean: true
      - name: Restore main Dockerfile
        run: cp /tmp/docker/Dockerfile .
      - name: SHA
        id: sha
        run: echo "sha=$(/usr/bin/git log -1 --format='%H')" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cosign to sign container images
        uses: sigstore/cosign-installer@v3.7.0
      - name: Build and push container images
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/holos-run/holos:${{ steps.opts.outputs.tag}}
            ghcr.io/holos-run/holos:${{ steps.sha.outputs.sha}}
            quay.io/holos-run/holos:${{ steps.opts.outputs.tag}}
            quay.io/holos-run/holos:${{ steps.sha.outputs.sha}}
      - name: Sign with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          cosign sign --yes ghcr.io/holos-run/holos:${{ steps.opts.outputs.tag}}@${DIGEST}
          cosign sign --yes ghcr.io/holos-run/holos:${{ steps.sha.outputs.sha}}@${DIGEST}
          cosign sign --yes quay.io/holos-run/holos:${{ steps.opts.outputs.tag}}@${DIGEST}
          cosign sign --yes quay.io/holos-run/holos:${{ steps.sha.outputs.sha}}@${DIGEST}
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
      detail: ${{ steps.tags.outputs.detail }}
