---
# https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#how-to-use
name: Lint
"on":
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      ## Not needed on ubuntu-latest
      # - name: Install Packages
      #   run: sudo apt update && sudo apt -qq -y install git curl zip unzip tar bzip2 make

      - name: Install Tools
        run: make tools

      - name: Lint
        # golangci-lint runs in a separate workflow.
        run: make lint -o golangci-lint
