name: Publish

on:
  push:
    branches: ['main', 'publish']

jobs:
  publish:
    name: Publish
    runs-on: gha-rs
    steps:
      - name: Provide GPG and Git
        run: sudo apt update && sudo apt -qq -y install gnupg git curl zip unzip tar bzip2 make jq

      # Must come after git executable is provided
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - uses: ko-build/setup-ko@v0.7
        env:
          KO_DOCKER_REPO: quay.io/holos-run/holos

      - name: Publish
        env:
          auth_user: holos-run+pusher
          auth_token: ${{ secrets.QUAY_TOKEN }}
        run: |
          echo "${auth_token}" | ko login quay.io --username "${auth_user}" --password-stdin
          make image
