name: Unit Tests

on:
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    runs-on: gha-rs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Packages
        run: sudo apt update && sudo apt -qq -y install git curl zip unzip tar bzip2 make

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Tools
        run: |
          set -x
          make tools
          make buf
          go generate ./...
          make frontend
          go mod tidy

      - name: Test
        run: ./scripts/test
